[package]
name = "fmorency-release-test"
version = "1.0.2-rc.1" # managed by release.sh
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
